const cat = {
  tvAndAudio: "tvAndAudio",
  tvBox: "tvBox",
  powerTools: "powerTools",
  headphones: "headphones",
  cellPhones: "cellPhones",
  smartWatches: "smartWatches",
  gameAndVideo: "gameAndVideo",
  robotClean: "robotClean",
  sportWatches: "sportWatches",
  tablets: "tablets",
  computersAndLaptop: "computersAndLaptop",
  camerasAndPhotos: "camerasAndPhotos",
};
export const categories = [
  {
    _id: 1,
    name: "tvAndAudio",
    image:
      "https://bestmarka.ru/wp-content/uploads/2021/01/televizory-samsung-2.jpg",
    description: "Televisions and audio equipment for home entertainment.",
    _base: "tvAndAudio",
  },
  {
    _id: 2,
    name: "tvBox",
    image:
      "https://s13emagst.akamaized.net/products/15264/15263605/images/res_0721ff9bb75e2f4ed9d47a4c9a73bd2f.jpg",
    description:
      "Streaming and smart TV boxes for enhanced viewing experience.",
    _base: "tvBox",
  },
  {
    _id: 3,
    name: "powerTools",
    image: "https://img.moyo.ua/img/categories/4921/4921_1473863135_22.jpg",
    description: "Reliable power tools for home improvement and DIY projects.",
    _base: "powerTools",
  },
  {
    _id: 4,
    name: "headphones",
    image: "https://i.eldorado.ua/goods_images/1038998/6809007-1603720102.jpg",
    description: "High-quality headphones for music and gaming.",
    _base: "headphones",
  },
  {
    _id: 5,
    name: "cellPhones",
    image:
      "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-10/764/849/999/913/25/100039500627b0.jpeg",
    description: "Modern smartphones with advanced features.",
    _base: "cellPhones",
  },
  {
    _id: 6,
    name: "smartWatches",
    image: "https://img.ktc.ua/img/base/1/1/324461.jpg",
    description: "Smartwatches for fitness tracking and seamless connectivity.",
    _base: "smartWatches",
  },
  {
    _id: 7,
    name: "gameAndVideo",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.O4BbPtGhfOcmnEOvQ7pDygHaFj&pid=Api",
    description: "Gaming consoles and accessories for immersive video gaming.",
    _base: "gameAndVideo",
  },
  {
    _id: 8,
    name: "robotClean",
    image: "https://files.foxtrot.com.ua/PhotoNew/img_0_32422_208_2.jpg",
    description: "Smart robot cleaners for effortless home cleaning.",
    _base: "robotClean",
  },
  {
    _id: 9,
    name: "sportWatches",
    image: "https://content.rozetka.com.ua/goods/images/big/45256191.jpg",
    description: "Durable sports watches for outdoor adventures.",
    _base: "sportWatches",
  },
  {
    _id: 10,
    name: "tablets",
    image:
      "https://main-cdn.sbermegamarket.ru/upload/reviews/images/14288b/ed-d3/f1-47/29-8f/40-4d/04235/3a9da/14288bed-d3f1-4729-8f40-4d042353a9da_0.jpg",
    description: "Portable tablets for work, play, and creativity.",
    _base: "tablets",
  },
  {
    _id: 11,
    name: "computersAndLaptop",
    image: "https://img.moyo.ua/img/categories/3314/3314_1473862846_78.jpg",
    description: "Powerful computers and laptops for all your needs.",
    _base: "computersAndLaptop",
  },
  {
    _id: 12,
    name: "camerasAndPhotos",
    image: "https://content.rozetka.com.ua/goods/images/original/11963949.jpg",
    description: "Cameras and accessories for photography enthusiasts.",
    _base: "camerasAndPhotos",
  },
];

export const highlightsProducts = [
  {
    _id: 47,
    name: "tvAndAudio",
    title: "Experience Immersive Sound",
    buttonTitle: "Shop Now",
    image:
      "https://samoe.top/wp-content/uploads/2020/11/oled-lg-oled55c9p-54.6-scaled.jpeg",
    _base: "/product",
    color: "#FF5733",
  },
  {
    _id: 48,
    name: "smartWatches",
    title: "Stay Connected, Stay Fit",
    buttonTitle: "Discover More",
    image:
      "https://content2.rozetka.com.ua/goods/images/original/268494143.jpg",
    _base: "/products",
    color: "#28A745",
  },
  {
    _id: 49,
    name: "camerasAndPhotos",
    title: "Capture Every Moment",
    buttonTitle: "Explore Cameras",
    image:
      "https://s13emagst.akamaized.net/products/54428/54427026/images/res_9c33ea66761bcc98009b3943012511b7.png",
    _base: "/product",
    color: "#FFC107",
  },
  {
    _id: 50,
    name: "headphones",
    title: "Unleash Your Music",
    buttonTitle: "View Headphones",
    image:
      "https://tse3.mm.bing.net/th?id=OIP.Lrjr1V6HnddglHIC-T_p_QHaK0&pid=Api",
    _base: "/product",
    color: "#6C63FF",
  },
  {
    _id: 51,
    name: "cellPhones",
    title: "Smartphones for Every Need",
    buttonTitle: "Buy Now",
    image:
      "https://cdn.ksyru0-fusion.fds.api.mi-img.com/b2c-mishop-pms-ru/pms_1648782872.32459166.png",
    _base: "/category/cellPhones",
    color: "#FF0000",
  },
];

export const blogsData = [
  {
    _id: 742,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg",
    title: "The Future of Artificial Intelligence in Everyday Life",
    _base: "artificialIntelligence",
    description:
      "Exploring how AI is transforming daily tasks and what to expect in the coming years.",
  },
  {
    _id: 743,
    image: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
    title: "Top 10 Gadgets to Watch in 2024",
    _base: "gadgets",
    description:
      "A curated list of the most anticipated tech gadgets set to release in 2024.",
  },
  {
    _id: 744,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg",
    title: "How 5G is Revolutionizing Mobile Connectivity",
    _base: "5GTechnology",
    description:
      "An in-depth look at the impact of 5G networks on communication and industries.",
  },
  {
    _id: 745,
    image: "https://images.pexels.com/photos/3861971/pexels-photo-3861971.jpeg",
    title: "The Rise of Electric Vehicles: What You Need to Know",
    _base: "electricVehicles",
    description:
      "Understanding the growth of EVs and their implications for the future of transportation.",
  },
  {
    _id: 746,
    image: "https://images.pexels.com/photos/3861970/pexels-photo-3861970.jpeg",
    title: "Virtual Reality: Beyond Gaming",
    _base: "virtualReality",
    description:
      "Exploring the diverse applications of VR technology in various sectors.",
  },
];

export const products = [
  {
    _id: 3825,
    name: "Samsung QLED Smart TV 55",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/ua/qe55q70dauxua/gallery/ua-qled-q70d-qe55q70dauxua-540627036?$650_519_PNG$",
      "https://images.samsung.com/is/image/samsung/p6pim/ua/qe55q60dauxua/gallery/ua-qled-q60d-qe55q60dauxua-541615873?$650_519_PNG$",
      "https://touch.com.ua/upload/resize_cache/webp/resize_cache/iblock/ef0/500_500_1/0682qwl6pok2bzcgy09g1pqh6z3mgzfh.webp",
    ],
    description:
      "55-inch QLED Smart TV from Samsung with 4K resolution and HDR support.",
    regularPrice: 25999,
    discountedPrice: 23999,
    quantity: 50,
    rating: 4.7,
    reviews: 134,
    category: "tvAndAudio",
    colors: ["Black", "Silver"],
    brand: "Samsung",
    isStock: true,
    overView:
      "Discover vibrant colors and sharp picture quality with the new Samsung QLED Smart TV.",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 3826,
    name: "Apple iPhone 14 Pro",
    images: [
      "https://gstore.ua/content/images/26/480x480l50nn0/apple-iphone-14-pro-128gb-silver-mq023-85982188264795.png",
      "https://cdn.new-brz.net/app/public/models/MQ0T3PX-A/large/w/230421160014880361.webp",
    ],
    description:
      "The new iPhone 14 Pro with a 6.1-inch display, A16 Bionic chip, and a triple camera setup.",
    regularPrice: 39999,
    discountedPrice: 37999,
    quantity: 30,
    rating: 4.8,
    reviews: 256,
    category: "cellPhones",
    colors: ["Deep Purple", "Silver", "Gold", "Space Black"],
    brand: "Apple",
    isStock: true,
    overView: "Experience power and elegance with the new iPhone 14 Pro.",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 3827,
    name: "Dell XPS 13 Laptop",
    images: [
      "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/13-9340/media-gallery/gray/touch-oled/notebook-xps-13-9340-t-oled-gy-gallery-2.psd?fmt=png-alpha&pscan=auto&scl=1&hei=320&wid=541&qlt=100,1&resMode=sharp2&size=541,320&chrss=full",
      "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/9345/media-gallery/touch/gray/notebook-xps-13-9345-t-gray-gallery-2-1.png?fmt=png-alpha&pscan=auto&scl=1&hei=320&wid=436&qlt=100,1&resMode=sharp2&size=436,320&chrss=full",
      "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9315/media-gallery/notebook-xps-9315-nt-blue-gallery-3.psd?fmt=png-alpha&pscan=auto&scl=1&hei=402&wid=575&qlt=100,1&resMode=sharp2&size=575,402&chrss=full",
    ],
    description:
      "Sleek Dell XPS 13 laptop with an Intel Core i7 processor, 16GB RAM, and 512GB SSD.",
    regularPrice: 45999,
    discountedPrice: 42999,
    quantity: 20,
    rating: 4.6,
    reviews: 98,
    category: "computersAndLaptop",
    colors: ["Silver", "Black"],
    brand: "Dell",
    isStock: true,
    overView: "Power and portability in one device – the Dell XPS 13.",
    isNew: false,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3828,
    name: "Sony WH-1000XM4 Headphones",
    images: [
      "https://media.wired.com/photos/5f2b2e792f0075bf6e0a1de6/master/pass/Gear-Sony-WH-1000XM4-1-SOURCE-Sony.jpg",
      "https://imageio.forbes.com/specials-images/imageserve/5f2c1f4101b4ac7f60809a60/Sony-WH-1000XM4-headphones--just-launched-/960x0.jpg?format=jpg&width=960",
      "https://i.insider.com/5f36a9e4e89ebf001f044924?width=1200&format=jpeg",
    ],
    description:
      "Wireless headphones with active noise cancellation and premium sound quality.",
    regularPrice: 9999,
    discountedPrice: 9499,
    quantity: 75,
    rating: 4.9,
    reviews: 412,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView: "Enjoy your music without interruptions with Sony WH-1000XM4.",
    isNew: false,
    _base: cat?.headphones,
  },
  {
    _id: 3829,
    name: "Fitbit Versa 3 Smartwatch",
    images: [
      "https://cdn.27.ua/sc--media--prod/default/bf/40/67/bf406785-5a37-4b99-9ef7-b9ee2d69205c.jpg",
      "https://a.allegroimg.com/s1080/117040/4cce1b874de595c735954680874c/Smartwatch-Fitbit-Versa-3-czarny-Material-paska-tworzywo-sztuczne",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc6rv3WoMY45tW9anyIaXz4-tqDeBsiAU5hg&s",
    ],
    description:
      "Smartwatch with built-in GPS, heart rate monitoring, and up to 6 days of battery life.",
    regularPrice: 7999,
    discountedPrice: 7499,
    quantity: 40,
    rating: 4.5,
    reviews: 189,
    category: "smartWatches",
    colors: ["Black", "Pink", "Blue"],
    brand: "Fitbit",
    isStock: true,
    overView: "Stay active and connected with the Fitbit Versa 3.",
    isNew: true,
    _base: cat?.smartWatches,
  },
  {
    _id: 3830,
    name: "Samsung Galaxy Tab S8",
    images: [
      "https://a.allegroimg.com/s1080/1199e7/91209e8c4681a482b20cc739f037/Samsung-Galaxy-Tab-S8-12-4-8-128GB-5G-Silver-Wbudowana-pamiec-128-GB",
      "https://apolo.com.ua/image/cache/catalog/Apolo2019/4/352563564-samsung-galaxy-tab-s8-plus-12-4-8-128gb-5g-pink-gold-sm-x806bida-500x500.jpg",
      "https://images.samsung.com/ua/galaxy-tab-s8/feature/buy/carousel/TabS8_S8+_allColorKV_WithSPen_MO.jpg",
    ],
    description:
      "12.4-inch Android tablet with 256GB storage and S Pen support.",
    regularPrice: 29999,
    discountedPrice: 27999,
    quantity: 60,
    rating: 4.6,
    reviews: 210,
    category: "tablets",
    colors: ["Graphite", "Silver", "Pink Gold"],
    brand: "Samsung",
    isStock: true,
    overView:
      "Enjoy productivity and creativity on the go with Samsung Galaxy Tab S8.",
    isNew: true,
    _base: cat?.tablets,
  },
  {
    _id: 3831,
    name: "Bose QuietComfort 45 Headphones",
    images: [
      "https://m.media-amazon.com/images/I/513SArZRYRL.jpg",
      "https://era-in-ear.com/wp-content/uploads/2022/01/Bose-QuietComfort-45.jpg",
      "https://i.moyo.ua/img/gallery/5022/54/1271476_middle.jpg",
    ],
    description:
      "Premium wireless headphones with active noise cancellation and unmatched comfort.",
    regularPrice: 34999,
    discountedPrice: 32999,
    quantity: 25,
    rating: 4.8,
    reviews: 156,
    category: "headphones",
    colors: ["Black", "White"],
    brand: "Bose",
    isStock: true,
    overView: "Experience supreme sound and comfort with Bose QuietComfort 45.",
    isNew: false,
    _base: cat?.headphones,
  },
  {
    _id: 3832,
    name: "HP Spectre x360 Laptop",
    images: [
      "https://www.hp.com/ca-en/shop/Html/Merch/Images/9B0L2UA-ABL_2_1750x1285.jpg",
      "https://www.hp.com/gb-en/shop/Html/Merch/Images/c08744066_1750x1285.jpg",
      "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08799380.png?impolicy=Png_Res&imwidth=270&imdensity=1",
    ],
    description:
      "Convertible 13-inch laptop with Intel Core i7 processor, 16GB RAM, and 512GB SSD.",
    regularPrice: 129999,
    discountedPrice: 124999,
    quantity: 15,
    rating: 4.7,
    reviews: 90,
    category: "computersAndLaptop",
    colors: ["Dark Ash Silver", "Poseidon Blue"],
    brand: "HP",
    isStock: true,
    overView: "Work or play from anywhere with the versatile HP Spectre x360.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3833,
    name: "Apple Watch Series 8",
    images: [
      "https://my-apple.com.ua/image/catalog/products/watch/series-8/product-red-1.png",
      "https://pixel.com.ua/image/cache/catalog/applewatch/series8/applewatchseries841mm-4-800x800.jpg",
      "https://mcstore.com.ua/news/wp-content/uploads/2022/08/Apple-Watch-Series-8-mc.jpg",
    ],
    description:
      "Smartwatch with advanced health and fitness features, including ECG and blood oxygen monitoring.",
    regularPrice: 46999,
    discountedPrice: 44999,
    quantity: 40,
    rating: 4.9,
    reviews: 300,
    category: "smartWatches",
    colors: ["Graphite", "Silver", "Midnight", "Starlight"],
    brand: "Apple",
    isStock: true,
    overView: "Stay healthy and connected with the Apple Watch Series 8.",
    isNew: true,
    _base: cat?.smartWatches,
  },
  {
    _id: 3834,
    name: "Sony PlayStation 5 Console",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQARF49bcbpxpXlyh643EeO6kd9ppR1flDLaw&s",
      "https://images.prom.ua/5014216807_w640_h640_playstation-5-blue-ray.jpg",
      "https://img.jabko.ua/image/cache//catalog/products/2024/09/110940/ps5-pro-3full.jpg.webp",
    ],
    description:
      "Next-gen gaming console with lightning-fast load times, immersive visuals, and exclusive games.",
    regularPrice: 49999,
    discountedPrice: 47999,
    quantity: 100,
    rating: 4.9,
    reviews: 890,
    category: "gameAndVideo",
    colors: ["White", "Black"],
    brand: "Sony",
    isStock: true,
    overView: "Experience gaming like never before with PlayStation 5.",
    isNew: true,
    _base: cat?.gameAndVideo,
  },
  {
    _id: 3835,
    name: "Xiaomi Mi 11 Ultra",
    images: [
      "https://wookie.com.ua/content/images/46/zashchitnyy-chekhol-unicase-rugged-guard-dlya-xiaomi-mi-11-ultra91795-36386306987696.jpg",
      "https://ireland.apollo.olxcdn.com/v1/files/tm5kljthgfzv-UA/image",
      "https://cdn.new-brz.net/app/public/models/MI11ULTRA-12-256CW/large/w/210621160009445136.webp",
    ],
    description:
      "Flagship smartphone with 6.81-inch AMOLED display, Snapdragon 888, and 108MP camera.",
    regularPrice: 74999,
    discountedPrice: 71999,
    quantity: 80,
    rating: 4.8,
    reviews: 360,
    category: "cellPhones",
    colors: ["Black", "White", "Green"],
    brand: "Xiaomi",
    isStock: true,
    overView:
      "Take your smartphone experience to the next level with the Mi 11 Ultra.",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 3836,
    name: "Sony WH-1000XM4",
    images: [
      "https://content1.rozetka.com.ua/goods/images/big/396467425.jpg",
      "https://avic.com.ua/assets/cache/products/234548/naushniki-sony-wh-1000xm4-black-19-prod_xl.jpg",
      "https://pcshop.ua/image/catalog/FotoOpis/Sony/WH-1000XM4%2023.jpg",
    ],
    description:
      "Industry-leading noise-canceling headphones with a 30-hour battery life.",
    regularPrice: 37999,
    discountedPrice: 34999,
    quantity: 45,
    rating: 4.7,
    reviews: 215,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Get premium sound quality and noise-canceling features with Sony WH-1000XM4.",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 3837,
    name: "Lenovo ThinkPad X1 Carbon Gen 9",
    images: [
      "https://p1-ofp.static.pub/fes/cms/2022/03/17/pw5jy11vn8u0jbi3rdu3aq1ij4bl15411237.png",
      "https://p1-ofp.static.pub/medias/bWFzdGVyfHJvb3R8MjMwMTQxfGltYWdlL2pwZWd8aDQ1L2gxYy8xMTMzMjY5MTAwMTM3NC5qcGd8YzI3NmFhYzdjN2I4Nzc0ZjFlYzM0MWZiZDQ4MWJiMmRlYTVlOTEzNWJiNzA3MjlmMTY4ZjdlODI2ODcwOGEwNw/bWFzdGVyfH.jpg",
      "https://content2.rozetka.com.ua/goods/images/big/291232038.png",
    ],
    description:
      "Ultra-light and durable 14-inch laptop with Intel Core i7, 16GB RAM, and 512GB SSD.",
    regularPrice: 189999,
    discountedPrice: 179999,
    quantity: 30,
    rating: 4.8,
    reviews: 180,
    category: "computersAndLaptop",
    colors: ["Black"],
    brand: "Lenovo",
    isStock: true,
    overView:
      "The ultimate combination of performance and portability with Lenovo ThinkPad X1 Carbon.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3838,
    name: "Apple iPad Pro 12.9-inch",
    images: [
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-ipad-pro-12-wifi-spacegray-2021?wid=1150&hei=1150&fmt=jpeg&qlt=95&.v=1674663706569",
      "https://m.media-amazon.com/images/I/61ZYtF-byGL.jpg",
      "https://i.pcmag.com/imagery/reviews/01TBSjO8pGQCS6wWsZ315FS-2..v1569469987.jpg",
    ],
    description:
      "Powerful tablet with a 12.9-inch Liquid Retina XDR display, M1 chip, and 5G support.",
    regularPrice: 109999,
    discountedPrice: 104999,
    quantity: 25,
    rating: 4.9,
    reviews: 250,
    category: "tablets",
    colors: ["Space Gray", "Silver"],
    brand: "Apple",
    isStock: true,
    overView:
      "Maximize your creativity and productivity with the Apple iPad Pro.",
    isNew: true,
    _base: cat?.tablets,
  },
  {
    _id: 3839,
    name: "Sony Alpha 7C Camera",
    images: [
      "https://sony.scene7.com/is/image/sonyglobalsolutions/feature_04_mobile?$toutMobile$",
      "https://m.media-amazon.com/images/I/71vnW8Hjc6L.jpg",
      "https://m.media-amazon.com/images/I/71fzB04f1ML._AC_UF894,1000_QL80_.jpg",
    ],
    description:
      "Compact full-frame mirrorless camera with 24.2MP and 4K video recording.",
    regularPrice: 174999,
    discountedPrice: 169999,
    quantity: 15,
    rating: 4.8,
    reviews: 132,
    category: "camerasAndPhotos",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Capture every moment with precision and clarity using Sony Alpha 7C.",
    isNew: true,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 3840,
    name: "Samsung Galaxy S21 Ultra",
    images: [
      "https://content2.rozetka.com.ua/goods/images/big/413538398.jpg",
      "https://wefix.co.za/cdn/shop/products/Galaxy-S21-Ultra-Black.png?v=1700426091",
      "https://www.ipeople.in.ua/files/products/2604054965.800x600w.jpg",
    ],
    description:
      "The most powerful Galaxy S, featuring a 108MP camera and 6.8-inch Dynamic AMOLED 2X display.",
    regularPrice: 119999,
    discountedPrice: 109999,
    quantity: 60,
    rating: 4.7,
    reviews: 215,
    category: "cellPhones",
    colors: ["Phantom Black", "Phantom Silver"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy S21 Ultra offers ultimate performance with the best camera features.",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 3841,
    name: "Bose QuietComfort 35 II",
    images: [
      "https://hotline.ua/img/tx/240/2406954625.jpg",
      "https://portativ.ua/media/cache/images/1/image/750x700/602f0fa2c1f0d1ba5e241f914e856ff9/catalog/product/b/b8900cd94e4954835762fd6ed0fca6c0.jpg",
      "https://img.ktc.ua/img/base/1_295/1/181711.jpg",
    ],
    description:
      "Wireless noise-canceling headphones, with Alexa and Google Assistant built-in.",
    regularPrice: 29999,
    discountedPrice: 28999,
    quantity: 50,
    rating: 4.8,
    reviews: 180,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Bose",
    isStock: true,
    overView:
      "Bose QuietComfort 35 II provides unparalleled noise-canceling technology and sound quality.",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 3842,
    name: "Apple MacBook Pro 13-inch",
    images: [
      "https://bigmag.ua/image/cache/catalog/image/MacBook/2022/Apple-MacBook-Pro-13-Silver-2022-MNEP3/Product/Apple-MacBook-Pro-13-Silver-2022-MNEP3-1-2000x2000.png",
      "https://bigmag.ua/image/cache/catalog/archive/data/1c-macbook/GGKJV/22-800x600-2000x2000.jpg",
      "https://my-apple.com.ua/image/catalog/products/mac/macbook-pro/macbook-pro-13-2020/space-gray-1.png",
    ],
    description:
      "13-inch MacBook Pro with Apple M1 chip, Retina display, and up to 20 hours of battery life.",
    regularPrice: 129999,
    discountedPrice: 124999,
    quantity: 40,
    rating: 4.9,
    reviews: 230,
    category: "computersAndLaptop",
    colors: ["Space Gray", "Silver"],
    brand: "Apple",
    isStock: true,
    overView:
      "Powerful performance and long battery life with the new Apple M1 chip in the MacBook Pro.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3843,
    name: "Microsoft Surface Pro 7",
    images: [
      "https://www.cnet.com/a/img/resize/a0bf6e138d8c0edf3ae0709e1a5fece3fcd11a3d/hub/2019/10/21/6cdfa05c-6e0a-4111-bb38-e1cf6072ba8a/19-surface-pro-7.jpg?auto=webp&fit=crop&height=900&width=1200",
      "https://a.allegroimg.com/s1080/1e9313/3df93695403d9acbb43bf51b8096",
      "https://edtechmagazine.com/k12/sites/edtechmagazine.com.k12/files/styles/cdw_hero/public/articles/%5Bcdw_tech_site%3Afield_site_shortname%5D/202012/ETQ420_Microsoft%20Surface%20Pro%207%20Powers%20Distance%20Learning_ProductReview_Hero.jpg?itok=TR1U8lFy",
    ],
    description:
      "2-in-1 laptop with a 12.3-inch touchscreen, Intel Core i5, and up to 10.5 hours of battery life.",
    regularPrice: 89999,
    discountedPrice: 84999,
    quantity: 25,
    rating: 4.6,
    reviews: 175,
    category: "computersAndLaptop",
    colors: ["Platinum", "Matte Black"],
    brand: "Microsoft",
    isStock: true,
    overView:
      "The Microsoft Surface Pro 7 offers exceptional versatility with the power of a laptop and portability of a tablet.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3844,
    name: "Canon EOS 90D",
    images: [
      "https://i1.adis.ws/i/canon/eos-90d_fergus_kennedy_ambient_4030_c4ee8d74f45a4af2b6ef0bef3569630d?$hero-header-full-16by9-dt-jpg$",
      "https://amateurphotographer.com/wp-content/uploads/sites/7/2019/10/4R2A7060-scaled.jpg?w=1024",
      "https://3.img-dpreview.com/files/p/E~TS940x788~articles/5517326302/product/CanonEOS90D-beauty-02.jpeg",
    ],
    description:
      "The Canon EOS 90D is a DSLR camera that features a 32.5MP sensor, 4K video recording, and advanced autofocus.",
    regularPrice: 119999,
    discountedPrice: 109999,
    quantity: 15,
    rating: 4.7,
    reviews: 120,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Canon",
    isStock: true,
    overView: "Capture high-quality photos and videos with Canon EOS 90D.",
    isNew: true,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 3845,
    name: "Sony WH-1000XM5",
    images: [
      "https://i.ytimg.com/vi/6CsJZxfZsL0/maxresdefault.jpg",
      "https://i.moyo.ua/img/gallery/6139/9/2213001_zoom.jpg",
      "https://www.sony.ua/image/6145c1d32e6ac8e63a46c912dc33c5bb?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF",
    ],
    description:
      "Premium noise-canceling over-ear headphones with long-lasting comfort and 30 hours of battery life.",
    regularPrice: 34999,
    discountedPrice: 32999,
    quantity: 100,
    rating: 4.8,
    reviews: 540,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Industry-leading noise cancellation with exceptional sound quality for an immersive listening experience.",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 3846,
    name: "Apple iPad Pro 12.9-inch",
    images: [
      "https://grokholsky.com/uploads/products/590-590/66c887ca94feb-2024-08-23-03-59-54.webp",
      "https://grokholsky.com/uploads/products/590-590/66c887ca94f8c-2024-08-23-03-59-54.webp",
      "https://macplanet.ua/images/product/4703/gallery/16551/original.jpg?_=1339197207",
    ],
    description:
      "12.9-inch iPad Pro with M1 chip, Liquid Retina XDR display, and up to 2TB storage option.",
    regularPrice: 109999,
    discountedPrice: 99999,
    quantity: 50,
    rating: 4.9,
    reviews: 320,
    category: "tablets",
    colors: ["Silver", "Space Gray"],
    brand: "Apple",
    isStock: true,
    overView:
      "The most powerful iPad ever, featuring an advanced M1 chip and stunning display technology.",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 3847,
    name: "Microsoft Surface Laptop 4",
    images: [
      "https://pcshop.ua/image/cache/webp/catalog/tovar/noutbuk-microsoft-surface-laptop-4-15-5w6-00001-bh-mi5w600001-platinum-photo2-1024x768.webp",
      "https://notebook.lviv.ua/content/images/36/480x312l50nn0/95663345630981.jpg",
      "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RWBrzy?ver=85d4",
    ],
    description:
      "Laptop with 11th Gen Intel Core processor, 32GB RAM, and PixelSense touchscreen display.",
    regularPrice: 159999,
    discountedPrice: 149999,
    quantity: 25,
    rating: 4.7,
    reviews: 150,
    category: "computersAndLaptop",
    colors: ["Platinum", "Matte Black"],
    brand: "Microsoft",
    isStock: true,
    overView:
      "Designed for both work and play, Surface Laptop 4 combines stunning performance with elegance.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3848,
    name: "Nikon Z 6II",
    images: [
      "https://www.adorama.com/images/cms/25025O9W-D23A_76795.jpeg",
      "https://i.simpalsmedia.com/999.md/BoardImages/900x900/41ac762b458086a58e2915b662c8ceeb.jpg",
      "https://photographylife.com/cdn-cgi/imagedelivery/GrQZt6ZFhE4jsKqjDEtqRA/photographylife.com/2021/05/Nikon-Z6-II-Mirrorless-Camera.jpg/w=2048,h=1365",
    ],
    description:
      "24.5 MP mirrorless camera with a full-frame sensor and high-speed autofocus system.",
    regularPrice: 199999,
    discountedPrice: 189999,
    quantity: 20,
    rating: 4.9,
    reviews: 180,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Nikon",
    isStock: true,
    overView:
      "The Nikon Z 6II is built for professionals who need top-tier quality in both still photography and video.",
    isNew: true,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 3849,
    name: "Samsung Galaxy Tab S7+",
    images: [
      "https://applemir.com/files/products/galaxy_tab_s7plus_sm-t970_mysticblack.800x600w.jpg?78047f5ccc4d61eec754aa00ab770873",
      "https://www.samsung-online.com.ua/uploads/shop/products/large/846dec5680b9c05ed4731a6e6451ec3c.jpg",
      "https://fotomost.com.ua/content/images/33/536x536l50nn0/samsung-galaxy-tab-s7-plus-128gb-wi-fi-bronze-sm-t970nzna-80317172511108.jpg",
    ],
    description:
      "12.4-inch tablet with 120Hz Super AMOLED display and Qualcomm Snapdragon 865+.",
    regularPrice: 84999,
    discountedPrice: 79999,
    quantity: 35,
    rating: 4.6,
    reviews: 210,
    category: "tablets",
    colors: ["Mystic Black", "Mystic Bronze"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy Tab S7+ delivers incredible visuals with its large display and fast performance.",
    isNew: true,
    _base: cat?.tablets,
  },
  {
    _id: 3850,
    name: "Bose QuietComfort 35 II",
    images: [
      "https://i.ebayimg.com/thumbs/images/g/5-MAAOSwQJdnV-rF/s-l1200.jpg",
      "https://m.novostar.ua/photo/233/big/328723_3.jpg",
      "https://novostar.ua/photo/233/big/328724_1.jpg",
    ],
    description:
      "Wireless noise-canceling headphones with Alexa voice control and 20 hours of battery life.",
    regularPrice: 29999,
    discountedPrice: 27999,
    quantity: 150,
    rating: 4.7,
    reviews: 980,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Bose",
    isStock: true,
    overView:
      "The Bose QuietComfort 35 II provides world-class noise cancellation and premium sound quality.",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 3851,
    name: "Apple MacBook Air M2",
    images: [
      "https://dzvinok.ua/pub/media/catalog/product/cache/c687aa7517cf01e65c009f6943c2b1e9/a/p/apple_macbook_air_m2_a2682_mlxw3uaa_-foto2.webp",
      "https://yabloki.ua/media/cache/sylius_shop_product_original/0b/1b/macbook-air-13-apple-m2-256gb-midnight-2022-mly33-1.png.webp",
      "https://www.apple.com/newsroom/images/product/mac/standard/Apple-MacBook-Air-M2-availability-July-2022-macOS-Monterey_big.jpg.large.jpg",
    ],
    description:
      "13.6-inch MacBook Air with M2 chip, up to 512GB SSD, and 18 hours of battery life.",
    regularPrice: 124999,
    discountedPrice: 119999,
    quantity: 75,
    rating: 4.9,
    reviews: 450,
    category: "computersAndLaptop",
    colors: ["Midnight", "Starlight", "Space Gray"],
    brand: "Apple",
    isStock: true,
    overView:
      "Light, powerful, and completely reimagined with the M2 chip for unbeatable performance and efficiency.",
    isNew: true,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 3852,
    name: "Sony PlayStation 5",
    images: [
      "https://bigmag.ua/image/cache/catalog/image/Product/Sony%20Playstation%205/PS%205%20Slim/ps5555slim-2000x2000.jpg",
      "https://super.com.ua/upload/iblock/7fe/7fefe78df0b4ecaae5145d02eadd645e.jpg",
      "https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21?$facebook$",
    ],
    description:
      "The next-generation gaming console with ultra-high-speed SSD and 4K gaming support.",
    regularPrice: 49999,
    discountedPrice: 46999,
    quantity: 200,
    rating: 4.8,
    reviews: 1200,
    category: "gameAndVideo",
    colors: ["White", "Black"],
    brand: "Sony",
    isStock: true,
    overView:
      "PS5 delivers lightning-fast load times and immersive 4K graphics for a truly next-gen gaming experience.",
    isNew: true,
    _base: cat?.gameAndVideo,
  },
  {
    _id: 3853,
    name: "Canon EOS 5D Mark IV",
    images: [
      "https://2.img-dpreview.com/files/p/E~TS590x0~articles/9882546842/sambeauty/4.jpeg",
      "https://d1rzxhvrtciqq1.cloudfront.net/uploads/images/listingimage/1007565/image/big-912610dd9fb73bfdd4e75c1aa8fa9ccd.jpg",
      "https://i.ebayimg.com/thumbs/images/g/jToAAOSwatNnU-eN/s-l1200.jpg",
    ],
    description:
      "Full-frame DSLR camera with 30.4 MP resolution and 4K video capabilities.",
    regularPrice: 329999,
    discountedPrice: 299999,
    quantity: 40,
    rating: 4.9,
    reviews: 250,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Canon",
    isStock: true,
    overView:
      "The Canon EOS 5D Mark IV offers professional-level image quality and exceptional video performance.",
    isNew: false,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 3854,
    name: "Samsung Galaxy Z Fold 5",
    images: [
      "https://bsmedia.business-standard.com/_media/bs/img/article/2023-04/21/full/1682069872-5363.jpg?im=FeatureCrop,size=(826,465)",
      "https://images.samsung.com/ua/smartphones/galaxy-fold5/images/galaxy-z-fold5-highlights-experience-dual-preview-tb.png?imbypass=true",
      "https://images.samsung.com/ae/smartphones/galaxy-z-fold5/images/galaxy-z-fold5-highlights-kv-a.jpg?imbypass=true",
    ],
    description: "Foldable smartphone with 7.6-inch display and 12GB RAM.",
    regularPrice: 179999,
    discountedPrice: 169999,
    quantity: 60,
    rating: 4.7,
    reviews: 500,
    category: "cellPhones",
    colors: ["Phantom Black", "Ivy Green", "Cream"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy Z Fold 5 brings a new level of foldable smartphone innovation with an ultra-clear display and multitasking capabilities.",
    isNew: true,
    _base: cat?.cellPhones,
  },
];
