const cat = {
  tvAndAudio: "tvAndAudio",
  tvBox: "tvBox",
  powerTools: "powerTools",
  headphones: "headphones",
  cellPhones: "cellPhones",
  smartWatches: "smartWatches",
  gameAndVideo: "gameAndVideo",
  robotClean: "robotClean",
  sportWatches: "sportWatches",
  tablets: "tablets",
  computersAndLaptop: "computersAndLaptop",
  camerasAndPhotos: "camerasAndPhotos",
};
export const categories = [
  {
    _id: 1,
    name: "tvAndAudio",
    image:
      "https://bestmarka.ru/wp-content/uploads/2021/01/televizory-samsung-2.jpg",
    description: "Televisions and audio equipment for home entertainment.",
    _base: "tvAndAudio",
  },
  {
    _id: 2,
    name: "tvBox",
    image:
      "https://s13emagst.akamaized.net/products/15264/15263605/images/res_0721ff9bb75e2f4ed9d47a4c9a73bd2f.jpg",
    description:
      "Streaming and smart TV boxes for enhanced viewing experience.",
    _base: "tvBox",
  },
  {
    _id: 3,
    name: "powerTools",
    image: "https://img.moyo.ua/img/categories/4921/4921_1473863135_22.jpg",
    description: "Reliable power tools for home improvement and DIY projects.",
    _base: "powerTools",
  },
  {
    _id: 4,
    name: "headphones",
    image: "https://i.eldorado.ua/goods_images/1038998/6809007-1603720102.jpg",
    description: "High-quality headphones for music and gaming.",
    _base: "headphones",
  },
  {
    _id: 5,
    name: "cellPhones",
    image:
      "https://main-cdn.sbermegamarket.ru/big1/hlr-system/-10/764/849/999/913/25/100039500627b0.jpeg",
    description: "Modern smartphones with advanced features.",
    _base: "cellPhones",
  },
  {
    _id: 6,
    name: "smartWatches",
    image: "https://img.ktc.ua/img/base/1/1/324461.jpg",
    description: "Smartwatches for fitness tracking and seamless connectivity.",
    _base: "smartWatches",
  },
  {
    _id: 7,
    name: "gameAndVideo",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.O4BbPtGhfOcmnEOvQ7pDygHaFj&pid=Api",
    description: "Gaming consoles and accessories for immersive video gaming.",
    _base: "gameAndVideo",
  },
  {
    _id: 8,
    name: "robotClean",
    image: "https://files.foxtrot.com.ua/PhotoNew/img_0_32422_208_2.jpg",
    description: "Smart robot cleaners for effortless home cleaning.",
    _base: "robotClean",
  },
  {
    _id: 9,
    name: "sportWatches",
    image: "https://content.rozetka.com.ua/goods/images/big/45256191.jpg",
    description: "Durable sports watches for outdoor adventures.",
    _base: "sportWatches",
  },
  {
    _id: 10,
    name: "tablets",
    image:
      "https://main-cdn.sbermegamarket.ru/upload/reviews/images/14288b/ed-d3/f1-47/29-8f/40-4d/04235/3a9da/14288bed-d3f1-4729-8f40-4d042353a9da_0.jpg",
    description: "Portable tablets for work, play, and creativity.",
    _base: "tablets",
  },
  {
    _id: 11,
    name: "computersAndLaptop",
    image: "https://img.moyo.ua/img/categories/3314/3314_1473862846_78.jpg",
    description: "Powerful computers and laptops for all your needs.",
    _base: "computersAndLaptop",
  },
  {
    _id: 12,
    name: "camerasAndPhotos",
    image: "https://content.rozetka.com.ua/goods/images/original/11963949.jpg",
    description: "Cameras and accessories for photography enthusiasts.",
    _base: "camerasAndPhotos",
  },
];

export const highlightsProducts = [
  {
    _id: 47,
    name: "tvAndAudio",
    title: "Experience Immersive Sound",
    buttonTitle: "Shop Now",
    image:
      "https://samoe.top/wp-content/uploads/2020/11/oled-lg-oled55c9p-54.6-scaled.jpeg",
    _base: "/product",
    color: "#FF5733",
  },
  {
    _id: 48,
    name: "smartWatches",
    title: "Stay Connected, Stay Fit",
    buttonTitle: "Discover More",
    image:
      "https://content2.rozetka.com.ua/goods/images/original/268494143.jpg",
    _base: "/products",
    color: "#28A745",
  },
  {
    _id: 49,
    name: "camerasAndPhotos",
    title: "Capture Every Moment",
    buttonTitle: "Explore Cameras",
    image:
      "https://s13emagst.akamaized.net/products/54428/54427026/images/res_9c33ea66761bcc98009b3943012511b7.png",
    _base: "/product",
    color: "#FFC107",
  },
  {
    _id: 50,
    name: "headphones",
    title: "Unleash Your Music",
    buttonTitle: "View Headphones",
    image:
      "https://tse3.mm.bing.net/th?id=OIP.Lrjr1V6HnddglHIC-T_p_QHaK0&pid=Api",
    _base: "/product",
    color: "#6C63FF",
  },
  {
    _id: 51,
    name: "cellPhones",
    title: "Smartphones for Every Need",
    buttonTitle: "Buy Now",
    image:
      "https://cdn.ksyru0-fusion.fds.api.mi-img.com/b2c-mishop-pms-ru/pms_1648782872.32459166.png",
    _base: "/category/cellPhones",
    color: "#FF0000",
  },
];

export const blogsData = [
  {
    _id: 742,
    image: "https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg",
    title: "The Future of Artificial Intelligence in Everyday Life",
    _base: "artificialIntelligence",
    description:
      "Exploring how AI is transforming daily tasks and what to expect in the coming years.",
  },
  {
    _id: 743,
    image: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
    title: "Top 10 Gadgets to Watch in 2024",
    _base: "gadgets",
    description:
      "A curated list of the most anticipated tech gadgets set to release in 2024.",
  },
  {
    _id: 744,
    image: "https://images.pexels.com/photos/3861972/pexels-photo-3861972.jpeg",
    title: "How 5G is Revolutionizing Mobile Connectivity",
    _base: "5GTechnology",
    description:
      "An in-depth look at the impact of 5G networks on communication and industries.",
  },
  {
    _id: 745,
    image: "https://images.pexels.com/photos/3861971/pexels-photo-3861971.jpeg",
    title: "The Rise of Electric Vehicles: What You Need to Know",
    _base: "electricVehicles",
    description:
      "Understanding the growth of EVs and their implications for the future of transportation.",
  },
  {
    _id: 746,
    image: "https://images.pexels.com/photos/3861970/pexels-photo-3861970.jpeg",
    title: "Virtual Reality: Beyond Gaming",
    _base: "virtualReality",
    description:
      "Exploring the diverse applications of VR technology in various sectors.",
  },
];

export const products = [
  {
    _id: 3825,
    name: "Samsung QLED Smart TV 55",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/ua/qa55q60aauxua/gallery/ua-qled-q60a-qa55q60aauxua-431612-ua.jpg",
      "https://images.samsung.com/is/image/samsung/p6pim/ua/qa55q60aauxua/gallery/ua-qled-q60a-qa55q60aauxua-431610-ua.jpg",
    ],
    description:
      "55-inch QLED Smart TV from Samsung with 4K resolution and HDR support.",
    regularPrice: 25999,
    discountedPrice: 23999,
    quantity: 50,
    rating: 4.7,
    reviews: 134,
    category: "tvAndAudio",
    colors: ["Black", "Silver"],
    brand: "Samsung",
    isStock: true,
    overView:
      "Discover vibrant colors and sharp picture quality with the new Samsung QLED Smart TV.",
    isNew: true,
    _base: "tvAndAudio",
  },
  {
    _id: 3826,
    name: "Apple iPhone 14 Pro",
    images: [
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-pro-max-deep-purple-select?wid=940&hei=1112&fmt=png-alpha&.v=1660753619946",
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-14-pro-deep-purple-select?wid=940&hei=1112&fmt=png-alpha&.v=1660753619932",
    ],
    description:
      "The new iPhone 14 Pro with a 6.1-inch display, A16 Bionic chip, and a triple camera setup.",
    regularPrice: 39999,
    discountedPrice: 37999,
    quantity: 30,
    rating: 4.8,
    reviews: 256,
    category: "cellPhones",
    colors: ["Deep Purple", "Silver", "Gold", "Space Black"],
    brand: "Apple",
    isStock: true,
    overView: "Experience power and elegance with the new iPhone 14 Pro.",
    isNew: true,
    _base: "cellPhones",
  },
  {
    _id: 3827,
    name: "Dell XPS 13 Laptop",
    images: [
      "https://i.dell.com/sites/csimages/Merchandizing_Imagery/all/xps-13-9310-laptop.jpg",
      "https://i.dell.com/sites/csimages/Merchandizing_Imagery/all/xps-13-9310-laptop-close.jpg",
    ],
    description:
      "Sleek Dell XPS 13 laptop with an Intel Core i7 processor, 16GB RAM, and 512GB SSD.",
    regularPrice: 45999,
    discountedPrice: 42999,
    quantity: 20,
    rating: 4.6,
    reviews: 98,
    category: "computersAndLaptop",
    colors: ["Silver", "Black"],
    brand: "Dell",
    isStock: true,
    overView: "Power and portability in one device – the Dell XPS 13.",
    isNew: false,
    _base: "computersAndLaptop",
  },
  {
    _id: 3828,
    name: "Sony WH-1000XM4 Headphones",
    images: [
      "https://www.sony.com/image/sony-wh-1000xm4-black.jpg",
      "https://www.sony.com/image/sony-wh-1000xm4-silver.jpg",
    ],
    description:
      "Wireless headphones with active noise cancellation and premium sound quality.",
    regularPrice: 9999,
    discountedPrice: 9499,
    quantity: 75,
    rating: 4.9,
    reviews: 412,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView: "Enjoy your music without interruptions with Sony WH-1000XM4.",
    isNew: false,
    _base: "headphones",
  },
  {
    _id: 3829,
    name: "Fitbit Versa 3 Smartwatch",
    images: [
      "https://static.fitbit.com/fitbit-versa-3.jpg",
      "https://static.fitbit.com/fitbit-versa-3-front.jpg",
    ],
    description:
      "Smartwatch with built-in GPS, heart rate monitoring, and up to 6 days of battery life.",
    regularPrice: 7999,
    discountedPrice: 7499,
    quantity: 40,
    rating: 4.5,
    reviews: 189,
    category: "smartWatches",
    colors: ["Black", "Pink", "Blue"],
    brand: "Fitbit",
    isStock: true,
    overView: "Stay active and connected with the Fitbit Versa 3.",
    isNew: true,
    _base: "smartWatches",
  },
  {
    _id: 3830,
    name: "Samsung Galaxy Tab S8",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/ua/galaxy-tab-s8-256gb-wi-fi-12-4-01.jpg",
      "https://images.samsung.com/is/image/samsung/p6pim/ua/galaxy-tab-s8-256gb-wi-fi-12-4-02.jpg",
    ],
    description:
      "12.4-inch Android tablet with 256GB storage and S Pen support.",
    regularPrice: 29999,
    discountedPrice: 27999,
    quantity: 60,
    rating: 4.6,
    reviews: 210,
    category: "tablets",
    colors: ["Graphite", "Silver", "Pink Gold"],
    brand: "Samsung",
    isStock: true,
    overView:
      "Enjoy productivity and creativity on the go with Samsung Galaxy Tab S8.",
    isNew: true,
    _base: "tablets",
  },
  {
    _id: 3831,
    name: "Bose QuietComfort 45 Headphones",
    images: [
      "https://www.bose.com/content/dam/bose/consumer/web/black/qc45-headphones.jpg",
      "https://www.bose.com/content/dam/bose/consumer/web/qc45-headphones-white.jpg",
    ],
    description:
      "Premium wireless headphones with active noise cancellation and unmatched comfort.",
    regularPrice: 34999,
    discountedPrice: 32999,
    quantity: 25,
    rating: 4.8,
    reviews: 156,
    category: "headphones",
    colors: ["Black", "White"],
    brand: "Bose",
    isStock: true,
    overView: "Experience supreme sound and comfort with Bose QuietComfort 45.",
    isNew: false,
    _base: "headphones",
  },
  {
    _id: 3832,
    name: "HP Spectre x360 Laptop",
    images: [
      "https://www.hp.com/us-en/shop/pdfs/spectre-x360-13.jpg",
      "https://www.hp.com/us-en/shop/pdfs/spectre-x360-13-02.jpg",
    ],
    description:
      "Convertible 13-inch laptop with Intel Core i7 processor, 16GB RAM, and 512GB SSD.",
    regularPrice: 129999,
    discountedPrice: 124999,
    quantity: 15,
    rating: 4.7,
    reviews: 90,
    category: "computersAndLaptop",
    colors: ["Dark Ash Silver", "Poseidon Blue"],
    brand: "HP",
    isStock: true,
    overView: "Work or play from anywhere with the versatile HP Spectre x360.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3833,
    name: "Apple Watch Series 8",
    images: [
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-series-8-front-graphite?wid=940&hei=1112&fmt=png-alpha&.v=1660731714374",
      "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/watch-series-8-front-silver?wid=940&hei=1112&fmt=png-alpha&.v=1660731714765",
    ],
    description:
      "Smartwatch with advanced health and fitness features, including ECG and blood oxygen monitoring.",
    regularPrice: 46999,
    discountedPrice: 44999,
    quantity: 40,
    rating: 4.9,
    reviews: 300,
    category: "smartWatches",
    colors: ["Graphite", "Silver", "Midnight", "Starlight"],
    brand: "Apple",
    isStock: true,
    overView: "Stay healthy and connected with the Apple Watch Series 8.",
    isNew: true,
    _base: "smartWatches",
  },
  {
    _id: 3834,
    name: "Sony PlayStation 5 Console",
    images: [
      "https://www.sony.com/is/image/sony/ps5-console.jpg",
      "https://www.sony.com/is/image/sony/ps5-console2.jpg",
    ],
    description:
      "Next-gen gaming console with lightning-fast load times, immersive visuals, and exclusive games.",
    regularPrice: 49999,
    discountedPrice: 47999,
    quantity: 100,
    rating: 4.9,
    reviews: 890,
    category: "gameAndVideo",
    colors: ["White", "Black"],
    brand: "Sony",
    isStock: true,
    overView: "Experience gaming like never before with PlayStation 5.",
    isNew: true,
    _base: "gameAndVideo",
  },
  {
    _id: 3835,
    name: "Xiaomi Mi 11 Ultra",
    images: [
      "https://i01.appmifile.com/5599/2021/02/19/a13c48fe59d3ac960cbec52db0cb58e5.jpg",
      "https://i01.appmifile.com/5519/2021/02/19/486d7848e7d3ac25d8db9222f3583832.jpg",
    ],
    description:
      "Flagship smartphone with 6.81-inch AMOLED display, Snapdragon 888, and 108MP camera.",
    regularPrice: 74999,
    discountedPrice: 71999,
    quantity: 80,
    rating: 4.8,
    reviews: 360,
    category: "cellPhones",
    colors: ["Black", "White", "Green"],
    brand: "Xiaomi",
    isStock: true,
    overView:
      "Take your smartphone experience to the next level with the Mi 11 Ultra.",
    isNew: true,
    _base: "cellPhones",
  },
  {
    _id: 3836,
    name: "Sony WH-1000XM4",
    images: [
      "https://www.sony.com/image/wh-1000xm4-p.jpg",
      "https://www.sony.com/image/wh-1000xm4-p2.jpg",
    ],
    description:
      "Industry-leading noise-canceling headphones with a 30-hour battery life.",
    regularPrice: 37999,
    discountedPrice: 34999,
    quantity: 45,
    rating: 4.7,
    reviews: 215,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Get premium sound quality and noise-canceling features with Sony WH-1000XM4.",
    isNew: true,
    _base: "headphones",
  },
  {
    _id: 3837,
    name: "Lenovo ThinkPad X1 Carbon Gen 9",
    images: [
      "https://www.lenovo.com/medias/lenovo-laptops-thinkpad-x1-carbon-gen-9-hero.png",
      "https://www.lenovo.com/medias/lenovo-laptops-thinkpad-x1-carbon-gen-9-angle.png",
    ],
    description:
      "Ultra-light and durable 14-inch laptop with Intel Core i7, 16GB RAM, and 512GB SSD.",
    regularPrice: 189999,
    discountedPrice: 179999,
    quantity: 30,
    rating: 4.8,
    reviews: 180,
    category: "computersAndLaptop",
    colors: ["Black"],
    brand: "Lenovo",
    isStock: true,
    overView:
      "The ultimate combination of performance and portability with Lenovo ThinkPad X1 Carbon.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3838,
    name: "Apple iPad Pro 12.9-inch",
    images: [
      "https://www.apple.com/v/ipad-pro/l/images/overview/hero/hero_endframe__b53d1b9b2182.jpg",
      "https://www.apple.com/v/ipad-pro/l/images/overview/hero/ipad-pro-12-9-hero__fghjbg7eiywm.jpg",
    ],
    description:
      "Powerful tablet with a 12.9-inch Liquid Retina XDR display, M1 chip, and 5G support.",
    regularPrice: 109999,
    discountedPrice: 104999,
    quantity: 25,
    rating: 4.9,
    reviews: 250,
    category: "tablets",
    colors: ["Space Gray", "Silver"],
    brand: "Apple",
    isStock: true,
    overView:
      "Maximize your creativity and productivity with the Apple iPad Pro.",
    isNew: true,
    _base: "tablets",
  },
  {
    _id: 3839,
    name: "Sony Alpha 7C Camera",
    images: [
      "https://www.sony.com/image/alpha-7c-camera.jpg",
      "https://www.sony.com/image/alpha-7c-camera2.jpg",
    ],
    description:
      "Compact full-frame mirrorless camera with 24.2MP and 4K video recording.",
    regularPrice: 174999,
    discountedPrice: 169999,
    quantity: 15,
    rating: 4.8,
    reviews: 132,
    category: "camerasAndPhotos",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Capture every moment with precision and clarity using Sony Alpha 7C.",
    isNew: true,
    _base: "camerasAndPhotos",
  },
  {
    _id: 3840,
    name: "Samsung Galaxy S21 Ultra",
    images: [
      "https://www.samsung.com/latin_en/smartphones/galaxy-s21-ultra-5g/_images/overview/hero-1.jpg",
      "https://www.samsung.com/latin_en/smartphones/galaxy-s21-ultra-5g/_images/overview/hero-2.jpg",
    ],
    description:
      "The most powerful Galaxy S, featuring a 108MP camera and 6.8-inch Dynamic AMOLED 2X display.",
    regularPrice: 119999,
    discountedPrice: 109999,
    quantity: 60,
    rating: 4.7,
    reviews: 215,
    category: "cellPhones",
    colors: ["Phantom Black", "Phantom Silver"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy S21 Ultra offers ultimate performance with the best camera features.",
    isNew: true,
    _base: "cellPhones",
  },
  {
    _id: 3841,
    name: "Bose QuietComfort 35 II",
    images: [
      "https://www.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/headphones/qc35ii/qc35ii-mic-hero@2x.jpg",
      "https://www.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/headphones/qc35ii/qc35ii-angle-hero@2x.jpg",
    ],
    description:
      "Wireless noise-canceling headphones, with Alexa and Google Assistant built-in.",
    regularPrice: 29999,
    discountedPrice: 28999,
    quantity: 50,
    rating: 4.8,
    reviews: 180,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Bose",
    isStock: true,
    overView:
      "Bose QuietComfort 35 II provides unparalleled noise-canceling technology and sound quality.",
    isNew: true,
    _base: "headphones",
  },
  {
    _id: 3842,
    name: "Apple MacBook Pro 13-inch",
    images: [
      "https://www.apple.com/v/macbook-pro-13/l/images/overview/hero_1x.jpg",
      "https://www.apple.com/v/macbook-pro-13/l/images/overview/hero_2x.jpg",
    ],
    description:
      "13-inch MacBook Pro with Apple M1 chip, Retina display, and up to 20 hours of battery life.",
    regularPrice: 129999,
    discountedPrice: 124999,
    quantity: 40,
    rating: 4.9,
    reviews: 230,
    category: "computersAndLaptop",
    colors: ["Space Gray", "Silver"],
    brand: "Apple",
    isStock: true,
    overView:
      "Powerful performance and long battery life with the new Apple M1 chip in the MacBook Pro.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3843,
    name: "Microsoft Surface Pro 7",
    images: [
      "https://www.microsoft.com/en-us/surface/pro7/media/surface-pro-7-hero.jpg",
      "https://www.microsoft.com/en-us/surface/pro7/media/surface-pro-7-front.jpg",
    ],
    description:
      "2-in-1 laptop with a 12.3-inch touchscreen, Intel Core i5, and up to 10.5 hours of battery life.",
    regularPrice: 89999,
    discountedPrice: 84999,
    quantity: 25,
    rating: 4.6,
    reviews: 175,
    category: "computersAndLaptop",
    colors: ["Platinum", "Matte Black"],
    brand: "Microsoft",
    isStock: true,
    overView:
      "The Microsoft Surface Pro 7 offers exceptional versatility with the power of a laptop and portability of a tablet.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3844,
    name: "Canon EOS 90D",
    images: [
      "https://www.usa.canon.com/internet/wcm/connect/us/153b207b-f6fb-4233-a35b-cfa0b237ebf2/canon-eos-90d-thumbnail.jpg",
      "https://www.usa.canon.com/internet/wcm/connect/us/7a1b6c8a-beb4-4782-90d5-1d1b9f812d3a/canon-eos-90d-angle.jpg",
    ],
    description:
      "The Canon EOS 90D is a DSLR camera that features a 32.5MP sensor, 4K video recording, and advanced autofocus.",
    regularPrice: 119999,
    discountedPrice: 109999,
    quantity: 15,
    rating: 4.7,
    reviews: 120,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Canon",
    isStock: true,
    overView: "Capture high-quality photos and videos with Canon EOS 90D.",
    isNew: true,
    _base: "camerasAndPhotos",
  },
  {
    _id: 3845,
    name: "Sony WH-1000XM5",
    images: [
      "https://www.sony.com/image/a0f8d9b3c6d7edb5ef41be81a3991212?fmt=pjpeg&wid=1500&hei=1500",
      "https://www.sony.com/image/da2beabb5b84c54795b18f29b6b1b153?fmt=pjpeg&wid=1500&hei=1500",
    ],
    description:
      "Premium noise-canceling over-ear headphones with long-lasting comfort and 30 hours of battery life.",
    regularPrice: 34999,
    discountedPrice: 32999,
    quantity: 100,
    rating: 4.8,
    reviews: 540,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Sony",
    isStock: true,
    overView:
      "Industry-leading noise cancellation with exceptional sound quality for an immersive listening experience.",
    isNew: true,
    _base: "headphones",
  },
  {
    _id: 3846,
    name: "Apple iPad Pro 12.9-inch",
    images: [
      "https://www.apple.com/v/ipad-pro-12.9/a/images/overview/ipad-pro-hero-large.jpg",
      "https://www.apple.com/v/ipad-pro-12.9/a/images/overview/ipad-pro-angle.jpg",
    ],
    description:
      "12.9-inch iPad Pro with M1 chip, Liquid Retina XDR display, and up to 2TB storage option.",
    regularPrice: 109999,
    discountedPrice: 99999,
    quantity: 50,
    rating: 4.9,
    reviews: 320,
    category: "tablets",
    colors: ["Silver", "Space Gray"],
    brand: "Apple",
    isStock: true,
    overView:
      "The most powerful iPad ever, featuring an advanced M1 chip and stunning display technology.",
    isNew: true,
    _base: "tablets",
  },
  {
    _id: 3847,
    name: "Microsoft Surface Laptop 4",
    images: [
      "https://www.microsoft.com/en-us/surface/assets/images/surface-laptop-4/product/surface-laptop-4-color-options-hero.jpg",
      "https://www.microsoft.com/en-us/surface/assets/images/surface-laptop-4/product/surface-laptop-4-angle.jpg",
    ],
    description:
      "Laptop with 11th Gen Intel Core processor, 32GB RAM, and PixelSense touchscreen display.",
    regularPrice: 159999,
    discountedPrice: 149999,
    quantity: 25,
    rating: 4.7,
    reviews: 150,
    category: "computersAndLaptop",
    colors: ["Platinum", "Matte Black"],
    brand: "Microsoft",
    isStock: true,
    overView:
      "Designed for both work and play, Surface Laptop 4 combines stunning performance with elegance.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3848,
    name: "Nikon Z 6II",
    images: [
      "https://cdn-01.kamera-express.nl/media/590x590/nikon-z6ii-2.jpg",
      "https://cdn-01.kamera-express.nl/media/590x590/nikon-z6ii-1.jpg",
    ],
    description:
      "24.5 MP mirrorless camera with a full-frame sensor and high-speed autofocus system.",
    regularPrice: 199999,
    discountedPrice: 189999,
    quantity: 20,
    rating: 4.9,
    reviews: 180,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Nikon",
    isStock: true,
    overView:
      "The Nikon Z 6II is built for professionals who need top-tier quality in both still photography and video.",
    isNew: true,
    _base: "camerasAndPhotos",
  },
  {
    _id: 3849,
    name: "Samsung Galaxy Tab S7+",
    images: [
      "https://www.samsung.com/global/galaxy/galaxy-tab-s7/images/galaxy-tab-s7-plus-features.jpg",
      "https://www.samsung.com/global/galaxy/galaxy-tab-s7/images/galaxy-tab-s7-plus-side.jpg",
    ],
    description:
      "12.4-inch tablet with 120Hz Super AMOLED display and Qualcomm Snapdragon 865+.",
    regularPrice: 84999,
    discountedPrice: 79999,
    quantity: 35,
    rating: 4.6,
    reviews: 210,
    category: "tablets",
    colors: ["Mystic Black", "Mystic Bronze"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy Tab S7+ delivers incredible visuals with its large display and fast performance.",
    isNew: true,
    _base: "tablets",
  },
  {
    _id: 3850,
    name: "Bose QuietComfort 35 II",
    images: [
      "https://www.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/headphones/quietcomfort-35-ii/product_images/quietcomfort-35-ii-black-lifestyle-1200.jpg",
      "https://www.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/headphones/quietcomfort-35-ii/product_images/quietcomfort-35-ii-silver-lifestyle-1200.jpg",
    ],
    description:
      "Wireless noise-canceling headphones with Alexa voice control and 20 hours of battery life.",
    regularPrice: 29999,
    discountedPrice: 27999,
    quantity: 150,
    rating: 4.7,
    reviews: 980,
    category: "headphones",
    colors: ["Black", "Silver"],
    brand: "Bose",
    isStock: true,
    overView:
      "The Bose QuietComfort 35 II provides world-class noise cancellation and premium sound quality.",
    isNew: true,
    _base: "headphones",
  },
  {
    _id: 3851,
    name: "Apple MacBook Air M2",
    images: [
      "https://www.apple.com/v/macbook-air/m/images/overview/macbook-air_hero_large.jpg",
      "https://www.apple.com/v/macbook-air/m/images/overview/macbook-air_side_large.jpg",
    ],
    description:
      "13.6-inch MacBook Air with M2 chip, up to 512GB SSD, and 18 hours of battery life.",
    regularPrice: 124999,
    discountedPrice: 119999,
    quantity: 75,
    rating: 4.9,
    reviews: 450,
    category: "computersAndLaptop",
    colors: ["Midnight", "Starlight", "Space Gray"],
    brand: "Apple",
    isStock: true,
    overView:
      "Light, powerful, and completely reimagined with the M2 chip for unbeatable performance and efficiency.",
    isNew: true,
    _base: "computersAndLaptop",
  },
  {
    _id: 3852,
    name: "Sony PlayStation 5",
    images: [
      "https://www.playstation.com/en-us/support/images/ps5-console-1200x800.jpg",
      "https://www.playstation.com/en-us/support/images/ps5-console-angle-1200x800.jpg",
    ],
    description:
      "The next-generation gaming console with ultra-high-speed SSD and 4K gaming support.",
    regularPrice: 49999,
    discountedPrice: 46999,
    quantity: 200,
    rating: 4.8,
    reviews: 1200,
    category: "gameAndVideo",
    colors: ["White", "Black"],
    brand: "Sony",
    isStock: true,
    overView:
      "PS5 delivers lightning-fast load times and immersive 4K graphics for a truly next-gen gaming experience.",
    isNew: true,
    _base: "gameAndVideo",
  },
  {
    _id: 3853,
    name: "Canon EOS 5D Mark IV",
    images: [
      "https://www.canon-europe.com/media/9157/canon-eos-5d-mark-iv-main.jpg?as=webp&d=800px&dpr=2",
      "https://www.canon-europe.com/media/9158/canon-eos-5d-mark-iv-angle.jpg?as=webp&d=800px&dpr=2",
    ],
    description:
      "Full-frame DSLR camera with 30.4 MP resolution and 4K video capabilities.",
    regularPrice: 329999,
    discountedPrice: 299999,
    quantity: 40,
    rating: 4.9,
    reviews: 250,
    category: "camerasAndPhotos",
    colors: ["Black"],
    brand: "Canon",
    isStock: true,
    overView:
      "The Canon EOS 5D Mark IV offers professional-level image quality and exceptional video performance.",
    isNew: false,
    _base: "camerasAndPhotos",
  },
  {
    _id: 3854,
    name: "Samsung Galaxy Z Fold 5",
    images: [
      "https://www.samsung.com/us/smartphones/galaxy-z-fold5/images/hero-image.png",
      "https://www.samsung.com/us/smartphones/galaxy-z-fold5/images/folded-image.png",
    ],
    description: "Foldable smartphone with 7.6-inch display and 12GB RAM.",
    regularPrice: 179999,
    discountedPrice: 169999,
    quantity: 60,
    rating: 4.7,
    reviews: 500,
    category: "cellPhones",
    colors: ["Phantom Black", "Ivy Green", "Cream"],
    brand: "Samsung",
    isStock: true,
    overView:
      "The Galaxy Z Fold 5 brings a new level of foldable smartphone innovation with an ultra-clear display and multitasking capabilities.",
    isNew: true,
    _base: "cellPhones",
  },
];
